### ISSUE TITLE
Work plan

### ISSUE THREAD

**Issue by daniellm** [status-im/nim-eth-verkle#1]
Components and dependencies:

1. Bandersnatch
    - EC Embedded in BLS
    - Multi-scalar Multplication, de/Serialization
    - Implemented in Constantin

2.  (Advaita) Banderwagon
    - Most logic is in here
    - Need to add Decaf representation: https://hackmd.io/wliPP_RMT4emsucVuCqfHA?view#A-Decaf-Style-representation-of-cofactor-4-incomplete-twisted-Edwards-curves
    - map to curve
    - Merge into Constantin

3. (Agnish) IPA
    - First stage: implement over Bandersnatch
    - Second stage: implement over Banderwagon
    - Look at Gnark or go-ipa
    - Merge into Constantin

4.  (Eze) Pedersen commitments
    - Depends on IPA
    - Lagrange interpolation

5.  (Daniel) Verkle tree
    - Depends on IPA & Pedersen commitments
    - RNG (nimcrypto)
    - append to tree
    - compute root ...
    - Note: if we use nbindgen it's at "Verkle Tree" level

6. (Naman) Comparative tests with other Verkle implementations

7. Integration in Nimbus-eth1 / testnet

**Comment by Godspower-Eze** [comment]
You can assign 4 to me while I wait for access to the recording
