### ISSUE TITLE
Testing the Verkle Trie Implementation 

### ISSUE THREAD

**Issue by advaita-saha** [status-im/nim-eth-verkle#16]
# Testing
The current **_Verkle Trie_** implementation is capable of all the trie operations but does not support the **Stateless** feature, it is yet to be added.

### Tests
The correctness of the tree root commiment have already been tested w.r.t `go-verkle` 
For testing the on the broader perspective we are supposed to test the follows
- [x] Tree Insertions correctness and edge cases
- [x] Cached commitment checks in Branch Nodes ( Internal Nodes )
- [x] Deletion operations 

For test vectors, it can be generated on our own also few can be taken from the `go-verkle` implementation from `tree_test.go`.

**Comment by advaita-saha** [comment]
# Testing Results 
<img width="1434" alt="Screenshot 2024-01-20 at 10 46 46 PM" src="https://github.com/status-im/nim-eth-verkle/assets/30210770/23411e1f-fcf6-48fe-8bb7-00da0ac087ed">

## Errors
All the operations are working perfectly fine from the correctness point of view. 
Except for the deletion of values with similar key path, for example let the tree have the following keys inserted with some values
- key1 --> `0x0105000000000000000000000000000000000000000000000000000000000000`
- key2 --> `0x0405000000000000000000000000000000000000000000000000000000000000`
Now if we go ahead and try to delete the key `0x0107000000000000000000000000000000000000000000000000000000000000`, this deletion **should NOT take place**, but for now deletion of this key is **NOT giving any error**.

**Comment by daniellm** [comment]
> All the operations are working perfectly fine from the correctness point of view.
> Except for the deletion of values with similar key path, for example let the tree have the following keys inserted with some values

Fixed in 6f5784ad6498c8433948e94dae3eec16efa98f03

**Comment by advaita-saha** [comment]
# All tests passing
<img width="405" alt="Screenshot 2024-01-21 at 1 14 29 PM" src="https://github.com/status-im/nim-eth-verkle/assets/30210770/6326398b-44fa-4ce5-a6ff-d182ee3af5a1">

The above tests are executed successfully in comparison the the `go-verkle` codebase
