### ISSUE TITLE
Update codebase with the new constantine version

### ISSUE THREAD

**Issue by advaita-saha** [status-im/nim-eth-verkle#26]
The PR https://github.com/mratsim/constantine/pull/392 in constantine introduces few generalisations & few type definition changes which would require changes in this codebase for Verkle Tries

**Comment by mratsim** [comment]
I have at least another PR as a follow-up for IPA.
And probably a third one for cosmetic, for example the `Point` and `Field` names are conflicting with other names in Constantine and will be renamed `EthVerklePoint` and `EthVerkleField` for disambiguation.

One thing I have to look into there is whether you need the affine, projective or both for the verkle tries.
